---
title: "scDHA Demonstration"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    horizontal_layout: fill
runtime: shiny
resource_files:
- install_packages.R
---

```{r setup, include=FALSE}
#When the package is loaded, it will check for C++ libtorch 
library(scDHA)
install.packages("scDHA")

# Shiny
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(shinyjs)

# install.packages("DT")
library(DT)

# Core
library(tidyverse)
# library(tidyquant)

# Interactive Visualizations
# library(plotly)

# Functions that perform the scDHA framework
source("run_scDHA.R")

```



```{r}
# Install rsconnect to deploy the ShinyApp to shinyapps.io for production ready
# install.packages('rsconnect')
```




```{r}

# By default
# sc <- load_data(dsname = "Goolam")

```



Sidebar {.sidebar data-width=350}
------------------------

```{r}
useShinyjs(rmd = TRUE)


# Select data source type
shinyWidgets::radioGroupButtons(
    inputId  = "datasource",
    label    = h4("Datasource"),
    choices  = c("Built-in Dataset" = "B", "Upload file" = "U"),
    selected = "B",
    status   = "primary", 
    justified = TRUE,
    checkIcon = list(
        yes = icon("ok", lib = "glyphicon"),
        no  = NULL
        )
)



# Get Build-in Datasets
data_package <- data(package = "scDHA")
builtin_datasets <- as.data.frame(data_package[[3]])$Item


# Built-in Dataset Widget
shinyWidgets::pickerInput(
    inputId  = "builtin_datasets", 
    width = "100%",
    label    = h4("Select a Dataset"), 
    choices  = unique(builtin_datasets), 
    multiple = FALSE
)


# Increase the file size limit
options(shiny.maxRequestSize = 1024^10)

# Upload dataset file
fileInput(  inputId = "upload_dataset", 
            width = "100%",
            label   = h4("Select your file (.rds, .rda, .csv, .tsv)"),
            multiple = FALSE,
            accept = c( 'text/csv', 
                        'text/comma-separated-values',
                        'text/tab-separated-values',
                        'text/plain',
                        '.csv',
                        '.tsv',
                        '.rds',
                        '.rda'),
                         buttonLabel = "Browse...",
                         placeholder = "No file selected"
)

br()

h4("Data & Pre-processing")

# Load Data Button 
actionButton(inputId = "load", label = "Load Data", icon = icon("database"), width = "49%") 

# "Autocencode" Button 
actionButton(inputId = "autoencode", label = "Autoencode", icon = icon("cog"), width = "49%")


br()
hr()
br()
```


```{r}
# Capture the changes in file upload

values <- reactiveValues(df_data = NULL, file_path = NULL)


observeEvent(input$upload_dataset, {
    req(input$upload_dataset)
    # values$df_data <- read.csv(input$upload_dataset$datapath)
    
    # Get uploaded file path
    values$file_path <- input$upload_dataset$datapath
})


```



```{r}

h4("Applications")

# "Cell segregation" Button 
actionButton(inputId = "cluster", label = "1. Segregation", icon = icon("table"), width = "49%")


# "Visualize" Button
actionButton(inputId = "visualize", label = "2. Visualize", icon = icon("line-chart"), width = "49%")

br()
br()
```

```{r}
# "Classification" Button 
actionButton(inputId = "classification", label = "3. Classification", icon = icon("list-alt"), width = "49%")


# "Time Trajectory" Button
actionButton(inputId = "pseudotime", label = "4. Time Trajectory", icon = icon("bolt"), width = "49%")

br()
br()
br()

```

```{r}

h4("Save your works")



# Save Button
actionButton(inputId = "save", label = "Save Result", icon = icon("save"), width = "49%")

# Reset Button
actionButton(inputId = "reset", label = "Reset", icon = icon("sync"), width = "49%")
```



```{r}

# Reset Button
observeEvent(eventExp = input$reset, handlerExpr = {
    
    # Reset option back to default, select built-in dataset
    updateRadioGroupButtons(session = session,
                             inputId = "datasource",
                             selected = "B")

    updatePickerInput(session = session, 
                      inputId = "builtin_datasets",
                      selected = "Goolam")
    
    # Load Goolam data by default
    shinyjs::delay(ms = 300, expr = {
        shinyjs::click(id = "load")
    })
    
})
```


Row {data-height=750}
-----------------------

### Single-Cell Data

```{r}

# Initially, sc is NULL

analysis_values <- reactiveValues(
    
    # Single Cell data
    sc = NULL,
    
    # Autoencoder
    scDHA_result = NULL,
    
    # Cell segregation
    rep2d = NULL,
    plot2d = NULL,
    
    # Cell classification
    idx = NULL,
        
    train.x = NULL,
    train.y = NULL,
    test.x  = NULL,
    test.y  = NULL,
    test.cell.ids = NULL,
        
    prediction = NULL,
        
    accuracy = NULL,
    predict_tbl = NULL,
    
    # Psuedo time inference
    inference_result = NULL,
    r2 = NULL
)


# "Load data" button click event
load_sc_data <- eventReactive(
    eventExpr = input$load, 
    valueExpr = {
        
        if (input$datasource == "B") {
            
            # sc <<- load_data(dsname = input$builtin_datasets)
            load_data(dsname = input$builtin_datasets)

        } else {
    
            # load_data(file = "data/yan.rds") values$file_path 
            # sc <<- load_data(file = values$file_path)
            load_data(file = values$file_path)
        }
        
  
    },
    ignoreNULL = TRUE
)

```


```{r}

sc_data_tbl <- reactive({
    
    # Save sc as global variable to use in next reactive sessions.
    #sc <<- load_sc_data()
    analysis_values$sc <- load_sc_data()
    
    # Transpose the data back to as original format to show in the Data table.
    
    # if (!is.null(sc)) {
    #    sc$data %>% t()
    
    if (!is.null(analysis_values$sc)) {
        analysis_values$sc$data %>% t()
    }
})
```


```{r}

# Render table output for SC Data

output$dt_sc_data <- DT::renderDataTable({
   sc_data_tbl() 
   
}, options = list(pageLength = 5))

DTOutput(outputId = "dt_sc_data")
```

Row {data-height=750}
-----------------------

### Single-Cell Data after Autoencoder - Latent (m = 15)

```{r}

# "Autoencode" button click event
autoencode_sc_data <- eventReactive(
    eventExpr = input$autoencode, 
    valueExpr = {
        
        # SC data after go through scDHA pipeline
        if (!is.null(analysis_values$sc))
            scDHA_pipeline(analysis_values$sc)    

    },
    ignoreNULL = TRUE
)

```


```{r}

scDHA_result_tbl <- reactive({
    
    # Save as global variable to use in next reactive sessions.
    # scDHA_result <<- autoencode_sc_data()
    analysis_values$scDHA_result <- autoencode_sc_data()
    
    # Latent 
    
    if (!is.null(analysis_values$scDHA_result)) {
       # scDHA_result$latent
        analysis_values$scDHA_result$latent
    }
})

```


```{r}

# Render table output for scDHA result

output$dt_scDHA_result <- DT::renderDataTable({
   scDHA_result_tbl() 
   
}, options = list(pageLength = 5))

DTOutput(outputId = "dt_scDHA_result")

```


Row {data-height=750}
-----------------------

### 1. Cell Segregation

```{r}

# "Cell Segregation" button click event
do_cluster <- eventReactive(
    eventExpr = input$cluster, 
    valueExpr = {
        
        # load sc data
        # sc <- load_sc_data()
        
        # scDHA function generates clustering result, the input matrix has rows as          samples and columns as genes, then merge the clustering result with the cell ID.
        if (!is.null(analysis_values$sc) && !is.null(analysis_values$scDHA_result))
            cell_segregation(analysis_values$sc, analysis_values$scDHA_result)
        
    },
    ignoreNULL = TRUE
)

```


```{r}

cluster_tbl <- reactive({
    
    # Perform clustering
    analysis_values$cluster <- do_cluster()
})

```

```{r}

output$dt_cluster <- DT::renderDataTable({
    cluster_tbl() 
    
}, options = list(pageLength = 5))

DTOutput(outputId = "dt_cluster")
```



### 2. Visualization

```{r}

# "Cell Segregation" button click event
do_visualize <- eventReactive(
    eventExpr = input$visualize, 
    valueExpr = {
        
        # Generate 2D representation, the input is the output from scDHA function
        if (!is.null(analysis_values$scDHA_result))
            analysis_values$rep2d <- gen_2d_rep(analysis_values$scDHA_result)
        
        if (!is.null(analysis_values$rep2d))
            analysis_values$plot2d <- visual_2d(analysis_values$rep2d, analysis_values$sc)
        
    },
    ignoreNULL = TRUE
)

```


```{r}


cluster_plot <- reactive({

    # Visualize 2D representations.
    do_visualize()
    
})
    

output$visual2d <- renderPlot({

    cluster_plot() 

    })

plotOutput(outputId = "visual2d")
```


### 3. Cell Classification

```{r}

# "Cell Classification" button click event
do_classification <- eventReactive(
    eventExpr = input$classification, 
    valueExpr = {
        
        # load sc data
        # sc <- load_sc_data()
        
        #Split data into training and testing sets
        set.seed(1)
        
        analysis_values$idx <- sample.int(nrow(analysis_values$sc$data), 
                                           size = round(nrow(analysis_values$sc$data)*0.75))
        
        analysis_values$train.x <- analysis_values$sc$data[analysis_values$idx, ]
        analysis_values$train.y <- analysis_values$sc$label[analysis_values$idx]
        analysis_values$test.x  <- analysis_values$sc$data[-analysis_values$idx, ]
        analysis_values$test.y  <- analysis_values$sc$label[-analysis_values$idx]
        analysis_values$test.cell.ids <- analysis_values$sc$cell.ids[-analysis_values$idx] 
        
        # Predict the labels of cells in testing set, the input matrices have rows as samples and columns as genes

        analysis_values$prediction <- cell_classification (
                                                    analysis_values$train.x, 
                                                    analysis_values$train.y, 
                                                    analysis_values$test.x) 
        
        # Calculate accuracy
        analysis_values$accuracy <- cal_accuracy (
                                                    analysis_values$test.y, 
                                                    analysis_values$prediction)
        
    },
    ignoreNULL = TRUE
)

```


```{r}

classification_tbl <- reactive({
    
    # Perform classification
    do_classification()
    
    # Generate result table
    analysis_values$predict_tbl <- bind_cols(analysis_values$test.cell.ids, 
                                              analysis_values$prediction, 
                                              analysis_values$test.y) %>% 
        
    set_names(c("Cell ID", "Predicted Label", "True Label")) %>%
        
    mutate(`Accurate` = case_when (
                        `Predicted Label` == `True Label` ~ 'TRUE',
                        TRUE ~ 'FALSE'
                ))
})

```

```{r}
accuracy_tbl <- reactive ({
    
    # Accuracy of the classification
    renderText("Accuracy Rate: ", analysis_values$accuracy)
})
```


```{r}

output$dt_classification <- DT::renderDataTable({
    
    classification_tbl() 
    
    
}, options = list(pageLength = 5))

DTOutput(outputId = "dt_classification")


renderText( 
    analysis_values$accuracy
    )


```



### 4. Pseudo Time-trajectory inference

```{r}

# "Cell Segregation" button click event
do_inference <- eventReactive(
    eventExpr = input$pseudotime, 
    valueExpr = {
        
        # load sc data
        # sc <- load_sc_data()
        
        # Generate 2D representation, the input is the output from scDHA function
        if (!is.null(analysis_values$scDHA_result))
            analysis_values$inference_result <- pseudo_time(analysis_values$scDHA_result)
        
        # Calculate r2
        if (!is.null(analysis_values$inference_result) && !is.null(analysis_values$sc))
            analysis_values$r2 <- cal_r2(analysis_values$sc, 
                                         analysis_values$inference_result)
       
        # Plot the result
        if (!is.null(analysis_values$inference_result) && !is.null(analysis_values$sc))
            pseudo_plot(analysis_values$sc, 
                        analysis_values$inference_result,
                        analysis_values$r2)
    },
    ignoreNULL = TRUE
)

```


```{r}


time_trajectory_plot <- reactive({

    # Visualize 2D representations.
    do_inference()
    
})
    

output$time_trajectory <- renderPlot({

    g2 <- time_trajectory_plot() 
    renderPrint(analysis_values$r2)
    
})

plotOutput(outputId = "time_trajectory")
```

```{r}

# "Save Result" button

observeEvent(eventExp = input$save, handlerExpr = {
    
    # Save
    result <- list()
    
    if (!is.null(analysis_values$sc))
          result <- append(result, analysis_values$sc)
      
    if (!is.null(analysis_values$scDHA_result))
        result <- append(result, analysis_values$scDHA_result)
     
    if (!is.null(analysis_values$cluster))
        result <- append(result, analysis_values$cluster)
     
    if (!is.null(analysis_values$rep2d))
        result <- append(result, analysis_values$rep2d)
    
    if (!is.null(analysis_values$plot2d))
        result <- append(result, analysis_values$plot2d)
    
    if (!is.null(analysis_values$idx))
        result <- append(result, analysis_values$idx)
    
    if (!is.null(analysis_values$train.x))
        result <- append(result, analysis_values$train.x)
    
    if (!is.null(analysis_values$train.y))
        result <- append(result, analysis_values$train.y)
    
    if (!is.null(analysis_values$test.x))
        result <- append(result, analysis_values$test.x)
    
    if (!is.null(analysis_values$test.y))
        result <- append(result, analysis_values$test.y)
     
    if (!is.null(analysis_values$test.cell.ids))
        result <- append(result, analysis_values$test.cell.ids)
    
    if (!is.null(analysis_values$prediction))
        result <- append(result, analysis_values$prediction)
    
    if (!is.null(analysis_values$accuracy))
        result <- append(result, analysis_values$accuracy)
    
        
    if (!is.null(analysis_values$predict_tbl))
        result <- append(result, analysis_values$predict_tbl)
    
        
    if (!is.nul(analysis_values$inference_result))
        result <- append(result, analysis_values$inference_result)
    
    if (!is.null(analysis_values$r2))
        result <- append(result, analysis_values$r2)


    readr::write_rds(result, file = "../results/myresult.rds")
})



```